import os
import re

import envfile  # noqa: F401  # loads repo-root .env before reading DATABASE_URL
import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

DATABASE_URL = (os.environ.get("DATABASE_URL") or "").strip()
if not DATABASE_URL.lower().startswith("postgres"):
    raise RuntimeError(
        "DATABASE_URL must be a PostgreSQL URL (postgresql://...). SQLite is no longer supported."
    )

IntegrityError = (psycopg.IntegrityError, psycopg.errors.UniqueViolation)
OperationalError = psycopg.OperationalError
DatabaseError = psycopg.Error

_pool = None

_LIKE_NOCASE = re.compile(r"LIKE\s+\?\s+COLLATE\s+NOCASE", re.IGNORECASE)
_ON_CONFLICT = re.compile(r"ON CONFLICT\s*\(", re.IGNORECASE)
_INSTR = re.compile(r"\binstr\s*\(", re.IGNORECASE)
_BEGIN_IMMEDIATE = re.compile(r"^\s*BEGIN(\s+IMMEDIATE|\s+TRANSACTION)?\s*;?\s*$", re.IGNORECASE)


def pk_autoincrement():
    return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def adapt_sql(sql):
    sql = sql.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    sql = _LIKE_NOCASE.sub("ILIKE ?", sql)
    sql = _ON_CONFLICT.sub("ON CONFLICT (", sql)
    sql = _INSTR.sub("strpos(", sql)
    out = []
    in_single = in_double = False
    i = 0
    while i < len(sql):
        ch = sql[i]
        if ch == "'" and not in_double:
            in_single = not in_single
        elif ch == '"' and not in_single:
            in_double = not in_double
        elif ch == "?" and not in_single and not in_double:
            out.append("%s")
            i += 1
            continue
        out.append(ch)
        i += 1
    return "".join(out)


class Row:
    def __init__(self, mapping):
        if mapping is None:
            self._data = {}
            self._keys = []
            self._ci = {}
            return
        if hasattr(mapping, "keys"):
            self._keys = list(mapping.keys())
            self._data = {key: mapping[key] for key in self._keys}
        else:
            self._keys = list(range(len(mapping)))
            self._data = {index: value for index, value in enumerate(mapping)}
        self._ci = {str(key).lower(): value for key, value in self._data.items()}

    def __getitem__(self, key):
        if isinstance(key, int):
            if key in self._data:
                return self._data[key]
            return self._data[self._keys[key]]
        if key in self._data:
            return self._data[key]
        return self._ci[str(key).lower()]

    def keys(self):
        return self._keys

    def __contains__(self, key):
        if isinstance(key, int):
            return 0 <= key < len(self._keys)
        return key in self._data or str(key).lower() in self._ci


def wrap_row(row):
    if row is None:
        return None
    if isinstance(row, Row):
        return row
    return Row(row)


class CompatCursor:
    def __init__(self, cursor):
        self._cursor = cursor
        self.lastrowid = getattr(cursor, "lastrowid", None)

    def execute(self, sql, params=None):
        if _BEGIN_IMMEDIATE.match(sql or ""):
            return self
        statement = adapt_sql(sql)
        if params is None:
            self._cursor.execute(statement)
        else:
            self._cursor.execute(statement, tuple(params) if not isinstance(params, tuple) else params)
        self.lastrowid = None
        stripped = statement.lstrip().upper()
        if (
            stripped.startswith("INSERT")
            and "RETURNING" not in stripped
            and "ON CONFLICT" not in stripped
        ):
            try:
                self._cursor.execute("SAVEPOINT malstar_lastval")
                ident = self._cursor.execute("SELECT lastval()").fetchone()
                self._cursor.execute("RELEASE SAVEPOINT malstar_lastval")
                if ident is not None:
                    self.lastrowid = ident[0] if not hasattr(ident, "keys") else next(iter(ident.values()))
            except Exception:
                self.lastrowid = None
                try:
                    self._cursor.execute("ROLLBACK TO SAVEPOINT malstar_lastval")
                    self._cursor.execute("RELEASE SAVEPOINT malstar_lastval")
                except Exception:
                    pass
        return self

    def executemany(self, sql, seq_of_params):
        self._cursor.executemany(adapt_sql(sql), list(seq_of_params))
        return self

    def fetchone(self):
        return wrap_row(self._cursor.fetchone())

    def fetchall(self):
        return [wrap_row(row) for row in self._cursor.fetchall()]

    def __iter__(self):
        for row in self._cursor:
            yield wrap_row(row)

    def close(self):
        self._cursor.close()


class CompatConnection:
    def __init__(self, conn):
        self._conn = conn
        self._managed = None

    def cursor(self):
        return CompatCursor(self._conn.cursor(row_factory=dict_row))

    def execute(self, sql, params=None):
        cursor = self.cursor()
        return cursor.execute(sql, params)

    def executemany(self, sql, seq_of_params):
        cursor = self.cursor()
        return cursor.executemany(sql, seq_of_params)

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        if self._managed is not None:
            self._managed.__exit__(None, None, None)
            self._managed = None
        else:
            self._conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            if exc_type:
                self.rollback()
            else:
                self.commit()
        finally:
            self.close()
        return False


def _pg_pool():
    global _pool
    if _pool is None:
        _pool = ConnectionPool(
            DATABASE_URL,
            min_size=1,
            max_size=8,
            timeout=30,
            open=True,
            kwargs={"autocommit": False, "row_factory": dict_row, "connect_timeout": 10},
        )
    return _pool


def connect(_db_path=None):
    managed = _pg_pool().connection()
    raw = managed.__enter__()
    wrapper = CompatConnection(raw)
    wrapper._managed = managed
    return wrapper


def ping():
    with connect() as conn:
        conn.execute("SELECT 1")


def table_exists(conn, name):
    row = conn.execute(
        """
        SELECT 1 FROM information_schema.tables
        WHERE table_schema='public' AND lower(table_name)=lower(?)
        """,
        (name,),
    ).fetchone()
    return bool(row)


def table_columns(conn, name):
    rows = conn.execute(
        """
        SELECT column_name FROM information_schema.columns
        WHERE table_schema='public' AND lower(table_name)=lower(?)
        """,
        (name,),
    ).fetchall()
    return {str(row[0]).lower() for row in rows}


def has_column(conn, table, column):
    columns = table_columns(conn, table)
    return column in columns or column.lower() in {str(item).lower() for item in columns}


def reset_identity(conn, *tables):
    for name in tables:
        row = conn.execute(
            "SELECT pg_get_serial_sequence(?, 'id')",
            (name,),
        ).fetchone()
        sequence = row[0] if row else None
        if sequence:
            conn.execute(f"SELECT setval('{sequence}', 1, false)")


def fetch_lastrowid(conn, cursor):
    if cursor.lastrowid:
        return cursor.lastrowid
    row = conn.execute("SELECT lastval()").fetchone()
    return row[0] if row else None
